---
grails:
  profile: web
  codegen:
    defaultPackage: onetomany
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
  groovy:
    template:
      check-template-location: false

---
grails:
    gorm:
        failOnError: true
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    hibernate:
        cache:
            queries: false
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grails
    username: root
    password: root
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    dbCreate: update

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/grails
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/grails
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/grails
